"""empty message

Revision ID: 0d598269f521
Revises: 98b5d8a2015b
Create Date: 2018-10-16 15:43:17.311805

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d598269f521'
down_revision = '98b5d8a2015b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mall', sa.Column('src_name', sa.String(length=45), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mall', 'src_name')
    # ### end Alembic commands ###
