"""empty message

Revision ID: 20455d2c8348
Revises: 09d70e0c7233
Create Date: 2018-09-27 12:09:00.951725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20455d2c8348'
down_revision = '09d70e0c7233'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fakeproduct', sa.Column('detail_image', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fakeproduct', 'detail_image')
    # ### end Alembic commands ###
