"""empty message

Revision ID: 37d5c3e61fbb
Revises: eaf05bfb9969
Create Date: 2018-10-05 10:47:07.388288

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37d5c3e61fbb'
down_revision = 'eaf05bfb9969'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('displaylocationcode')
    op.add_column('scripttags', sa.Column('JoinedLocationCode', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scripttags', 'JoinedLocationCode')
    op.create_table('displaylocationcode',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('mall_id', sa.VARCHAR(), nullable=False),
    sa.Column('shop_no', sa.INTEGER(), nullable=True),
    sa.Column('script_no', sa.INTEGER(), nullable=True),
    sa.Column('JoinedLocationCode', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('script_no')
    )
    # ### end Alembic commands ###
