"""empty message

Revision ID: 592cdad3cc72
Revises: 79bc429192d2
Create Date: 2018-09-28 14:32:31.006301

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '592cdad3cc72'
down_revision = '79bc429192d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scripttags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_no', sa.String(), nullable=True),
    sa.Column('script_no', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.String(), nullable=False),
    sa.Column('src', sa.String(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shop_no')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scripttags')
    # ### end Alembic commands ###
