"""empty message

Revision ID: 62d101b8dbd9
Revises: e0d6e7322053
Create Date: 2018-09-17 16:15:35.122059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62d101b8dbd9'
down_revision = 'e0d6e7322053'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mall', sa.Column('shop_no', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mall', 'shop_no')
    # ### end Alembic commands ###
