"""empty message

Revision ID: 677f1a5975de
Revises: 
Create Date: 2018-10-16 15:38:25.451548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '677f1a5975de'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mall',
    sa.Column('idx', sa.Integer(), nullable=False),
    sa.Column('mall_id', sa.String(length=45), nullable=False),
    sa.Column('shop_no', sa.Integer(), nullable=True),
    sa.Column('is_multi_shop', sa.String(length=4), nullable=True),
    sa.Column('lang', sa.String(length=4), nullable=True),
    sa.Column('access_token', sa.String(length=200), nullable=True),
    sa.Column('refresh_token', sa.String(length=200), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('refresh_token_expires_at', sa.DateTime(), nullable=True),
    sa.Column('src_name', sa.String(length=45), nullable=True),
    sa.PrimaryKeyConstraint('idx')
    )
    op.create_table('scripttags',
    sa.Column('idx', sa.Integer(), nullable=False),
    sa.Column('mall_idx', sa.Integer(), nullable=False),
    sa.Column('script_no', sa.String(length=45), nullable=True),
    sa.Column('client_id', sa.String(length=45), nullable=False),
    sa.Column('src_url', sa.String(length=200), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('JoinedLocationCode', sa.Text(), nullable=True),
    sa.Column('color', sa.String(length=45), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('transparency', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['mall_idx'], ['mall.idx'], ),
    sa.PrimaryKeyConstraint('idx'),
    sa.UniqueConstraint('script_no')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scripttags')
    op.drop_table('mall')
    # ### end Alembic commands ###
