"""empty message

Revision ID: 67d9dc703c80
Revises: 592cdad3cc72
Create Date: 2018-09-28 14:58:07.216852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67d9dc703c80'
down_revision = '592cdad3cc72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scripttags', sa.Column('mall_id', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'scripttags', ['mall_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'scripttags', type_='unique')
    op.drop_column('scripttags', 'mall_id')
    # ### end Alembic commands ###
