"""empty message

Revision ID: 79bc429192d2
Revises: 20455d2c8348
Create Date: 2018-09-27 14:44:33.952902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79bc429192d2'
down_revision = '20455d2c8348'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fakecustomer', sa.Column('phone_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fakecustomer', 'phone_number')
    # ### end Alembic commands ###
