"""empty message

Revision ID: 883b11f5ed90
Revises: c3d940c06be7
Create Date: 2018-09-18 12:00:52.413120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '883b11f5ed90'
down_revision = 'c3d940c06be7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mall', sa.Column('refresh_token_expires_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mall', 'refresh_token_expires_at')
    # ### end Alembic commands ###
