"""empty message

Revision ID: 98b5d8a2015b
Revises: 677f1a5975de
Create Date: 2018-10-16 15:39:22.195380

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '98b5d8a2015b'
down_revision = '677f1a5975de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mall', 'src_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mall', sa.Column('src_name', mysql.VARCHAR(length=45), nullable=True))
    # ### end Alembic commands ###
