"""empty message

Revision ID: c3d940c06be7
Revises: 62d101b8dbd9
Create Date: 2018-09-17 17:20:35.095172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3d940c06be7'
down_revision = '62d101b8dbd9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mall', sa.Column('is_multi_shop', sa.Boolean(), nullable=True))
    op.add_column('mall', sa.Column('lang', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mall', 'lang')
    op.drop_column('mall', 'is_multi_shop')
    # ### end Alembic commands ###
