"""empty message

Revision ID: eaf05bfb9969
Revises: 
Create Date: 2018-10-04 18:03:51.937971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eaf05bfb9969'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('displaylocationcode',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mall_id', sa.String(), nullable=False),
    sa.Column('shop_no', sa.Integer(), nullable=True),
    sa.Column('script_no', sa.Integer(), nullable=True),
    sa.Column('JoinedLocationCode', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('script_no')
    )
    op.create_table('fakecustomer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_no', sa.Integer(), nullable=True),
    sa.Column('member_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('available_mileage', sa.String(), nullable=True),
    sa.Column('group_no', sa.Integer(), nullable=True),
    sa.Column('member_authentication', sa.String(), nullable=True),
    sa.Column('use_blacklist', sa.String(), nullable=True),
    sa.Column('blacklist_type', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fakeorderitem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_no', sa.Integer(), nullable=True),
    sa.Column('item_no', sa.Integer(), nullable=True),
    sa.Column('order_item_code', sa.String(), nullable=True),
    sa.Column('product_no', sa.String(), nullable=True),
    sa.Column('product_code', sa.String(), nullable=True),
    sa.Column('eng_product_name', sa.String(), nullable=True),
    sa.Column('product_name', sa.String(), nullable=True),
    sa.Column('product_price', sa.String(), nullable=True),
    sa.Column('quantity', sa.String(), nullable=True),
    sa.Column('supplier_transaction_type', sa.Enum('D', 'P'), nullable=True),
    sa.Column('tracking_no', sa.String(), nullable=True),
    sa.Column('shipping_code', sa.String(), nullable=True),
    sa.Column('order_status', sa.Enum('N00', 'N10', 'N20', 'N21', 'N22', 'N30', 'N40'), nullable=True),
    sa.Column('status_code', sa.Enum('N1', 'N2', 'C1', 'C2', 'C3', 'E1'), nullable=True),
    sa.Column('status_text', sa.Enum('정상', '교환상품', '입금전 취소', '배송전취소', '반품', '교환'), nullable=True),
    sa.Column('shipping_company_id', sa.String(), nullable=True),
    sa.Column('shipping_company_name', sa.String(), nullable=True),
    sa.Column('shipping_company_code', sa.String(), nullable=True),
    sa.Column('original_item_no', sa.String(), nullable=True),
    sa.Column('ordered_date', sa.DateTime(), nullable=True),
    sa.Column('shipped_date', sa.DateTime(), nullable=True),
    sa.Column('delivered_date', sa.DateTime(), nullable=True),
    sa.Column('cancel_date', sa.DateTime(), nullable=True),
    sa.Column('return_request_date', sa.DateTime(), nullable=True),
    sa.Column('return_date', sa.DateTime(), nullable=True),
    sa.Column('cancel_request_date', sa.DateTime(), nullable=True),
    sa.Column('refund_date', sa.DateTime(), nullable=True),
    sa.Column('exchange_request_date', sa.DateTime(), nullable=True),
    sa.Column('exchange_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_no')
    )
    op.create_table('fakeorders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_no', sa.Integer(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('order_id', sa.String(), nullable=True),
    sa.Column('market_id', sa.String(), nullable=True),
    sa.Column('buyer_name', sa.String(), nullable=True),
    sa.Column('buyer_email', sa.String(), nullable=True),
    sa.Column('buyer_phone', sa.String(), nullable=True),
    sa.Column('buyer_cellphone', sa.String(), nullable=True),
    sa.Column('member_id', sa.String(), nullable=True),
    sa.Column('member_authentication', sa.Enum('T', 'B', 'J'), nullable=True),
    sa.Column('customer_group_no_when_ordering', sa.Integer(), nullable=True),
    sa.Column('bank_code', sa.String(), nullable=True),
    sa.Column('bank_code_name', sa.String(), nullable=True),
    sa.Column('payment_method', sa.String(), nullable=True),
    sa.Column('paid', sa.Enum('T', 'F'), nullable=True),
    sa.Column('order_date', sa.DateTime(), nullable=True),
    sa.Column('payment_date', sa.DateTime(), nullable=True),
    sa.Column('cancel_date', sa.DateTime(), nullable=True),
    sa.Column('shipping_status', sa.Enum('F', 'M', 'T', 'W'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id')
    )
    op.create_table('fakeproduct',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_no', sa.Integer(), nullable=True),
    sa.Column('product_no', sa.Integer(), nullable=True),
    sa.Column('product_code', sa.String(), nullable=True),
    sa.Column('custom_product_code', sa.String(), nullable=True),
    sa.Column('product_name', sa.String(), nullable=True),
    sa.Column('price', sa.String(), nullable=True),
    sa.Column('supply_price', sa.String(), nullable=True),
    sa.Column('display', sa.String(), nullable=True),
    sa.Column('detail_image', sa.String(), nullable=True),
    sa.Column('list_image', sa.String(), nullable=True),
    sa.Column('tiny_image', sa.String(), nullable=True),
    sa.Column('small_image', sa.String(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mall',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mall_id', sa.String(), nullable=False),
    sa.Column('shop_no', sa.Integer(), nullable=True),
    sa.Column('is_multi_shop', sa.String(), nullable=True),
    sa.Column('lang', sa.String(), nullable=True),
    sa.Column('access_token', sa.String(), nullable=True),
    sa.Column('refresh_token', sa.String(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('refresh_token_expires_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scripttags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mall_id', sa.String(), nullable=False),
    sa.Column('shop_no', sa.Integer(), nullable=True),
    sa.Column('script_no', sa.Integer(), nullable=True),
    sa.Column('client_id', sa.String(), nullable=False),
    sa.Column('src', sa.String(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('script_no')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scripttags')
    op.drop_table('mall')
    op.drop_table('fakeproduct')
    op.drop_table('fakeorders')
    op.drop_table('fakeorderitem')
    op.drop_table('fakecustomer')
    op.drop_table('displaylocationcode')
    # ### end Alembic commands ###
